netbox_reservations/urls.py
from django.urls import path

from netbox.views.generic import ObjectChangeLogView
from . import models, views


urlpatterns = (

    # Reservation
    path('reservations/', views.ReservationListView.as_view(), name='reservation_list'),
    path('reservations/add/', views.ReservationEditView.as_view(), name='reservation_add'),
    path('reservations/<int:pk>/', views.ReservationView.as_view(), name='reservation'),
    path('reservations/<int:pk>/edit/', views.ReservationEditView.as_view(), name='reservation_edit'),
    path('reservations/<int:pk>/delete/', views.ReservationDeleteView.as_view(), name='reservation_delete'),
    path('reservations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='reservation_changelog', kwargs={
        'model': models.Reservation
    }),

    # Claims
    path('claims/', views.ClaimListView.as_view(), name='claim_list'),
    path('claims/add/', views.ClaimEditView.as_view(), name='claim_add'),
    path('claims/<int:pk>/', views.ClaimView.as_view(), name='claim'),
    path('claims/<int:pk>/edit/', views.ClaimEditView.as_view(), name='claim_edit'),
    path('claims/<int:pk>/delete/', views.ClaimDeleteView.as_view(), name='claim_delete'),
    path('claims/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='claim_changelog', kwargs={
        'model': models.Claim
    }),

    # Tag Overview
    path('tags/', views.TagOverviewListView.as_view(), name='tag_overview_list'),

)

netbox_reservations/models.py
from tree_queries.fields import TreeNodeForeignKey
from tree_queries.models import TreeNode
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from tree_queries.query import TreeQuerySet

from netbox.models import NetBoxModel
from netbox_reservations.validators import ClaimValidator, ReservationValidator
from utilities.choices import ChoiceSet
from utilities.querysets import RestrictedQuerySet


class RestrictionChoices(ChoiceSet):
    key = 'Claim.restriction'

    CHOICES = [
        ('EXCLUSIVE', 'Exclusive', 'orange'),
        ('SHARED', 'Shared', 'green'),
    ]


class Reservation(NetBoxModel):
    name = models.CharField(
        max_length=100
    )
    description = models.CharField(
        max_length=500,
        blank=True
    )
    contact = models.ForeignKey(
        to='tenancy.Contact',
        on_delete=models.PROTECT,
        related_name='reservations',
    )
    tenant = models.ForeignKey(
        to='tenancy.Tenant',
        on_delete=models.PROTECT,
        related_name='reservations',
    )
    start_date = models.DateTimeField(
    )
    end_date = models.DateTimeField(
    )
    is_draft = models.BooleanField()

    clone_fields = (
        'contact', 'tenant', 'start_date', 'end_date', 'is_draft'
    )

    prerequisite_models = (
        'tenancy.Contact',
        'tenancy.Tenant',
    )

    def status(self):
        if self.is_draft:
            return 'Draft'
        elif self.start_date > timezone.now():
            return 'Planned'
        elif self.end_date < timezone.now():
            return 'Overdue'
        else:
            return 'Active'

    def clean(self):
        ReservationValidator().validate(self)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('plugins:netbox_reservations:reservation', args=[self.pk])


class ClaimQuerySet(TreeQuerySet, RestrictedQuerySet):
    def has_filters(self):
        return self._has_filters()


class Claim(NetBoxModel, TreeNode):
    reservation = models.ForeignKey(
        to=Reservation,
        on_delete=models.CASCADE,
        related_name='claims'
    )
    parent = TreeNodeForeignKey(
        "self",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("parent"),
        related_name="children",
    )
    tag = models.ForeignKey(
        to='extras.Tag',
        on_delete=models.PROTECT,
        related_name='claims',
    )
    restriction = models.CharField(
        max_length=20,
        choices=RestrictionChoices,
    )
    description = models.CharField(
        max_length=500,
        blank=True
    )

    clone_fields = (
        'reservation',
    )

    prerequisite_models = (
        'netbox_reservations.Reservation',
        'extras.Tag'
    )

    def clean(self):
        ClaimValidator().validate(self)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    class Meta:
        unique_together = ('reservation', 'tag')

    class MPTTMeta:
        order_insertion_by = ('tag',)

    def __str__(self):
        return f'Claim for {self.tag} by {self.reservation}'

    def get_absolute_url(self):
        return reverse('plugins:netbox_reservations:claim', args=[self.pk])

    def get_restriction_color(self):
        return RestrictionChoices.colors.get(self.restriction)

    def get_tag_color(self):
        return self.tag.color

netbox_reservations/templates/netbox_reservations/claim.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Claim</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Reservation</th>
              <td>
                <a href="{{ object.reservation.get_absolute_url }}">{{ object.reservation }}</a>
              </td>
            </tr>
            <tr>
              <th scope="row">Tag</th>
              <td>
                {% if object.tag %}
                  <a href="{{ object.tag.get_absolute_url }}">{{ object.tag }}</a>
                {% else %}
                  {{ ''|placeholder }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Restriction</th>
              <td>{{ object.get_restriction_display }}</td>
            </tr>
            <tr>
              <th scope="row">Description</th>
              <td>{{ object.description|placeholder }}</td>
            </tr>
            <tr>
              <th scope="row">Parent</th>
              <td>
                {% if object.parent %}
                  <a href="{{ object.parent.get_absolute_url }}">{{ object.parent }}</a>
                {% else %}
                  {{ ''|placeholder }}
                {% endif %}
              </td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      <!--{% include 'inc/panels/comments.html' %}-->
    </div>
  </div>
{% endblock content %}

netbox_reservations/templates/netbox_reservations/device_extend.html
{% load render_table from django_tables2 %}
<div class="card">
    <h5 class="card-header">
        Related Claims
    </h5>
    <div class="card-body">
        {% render_table related_claims_table 'inc/table.html' %}
    </div>
</div>

netbox_reservations/templates/netbox_reservations/extend_claims.html
{% load render_table from django_tables2 %}
<div class="card">
    <h5 class="card-header">
        Related Claims
    </h5>
    <div class="card-body">
        {% render_table related_claims_table 'inc/table.html' %}
    </div>
</div>

netbox_reservations/templates/netbox_reservations/extend_reservations.html
{% load render_table from django_tables2 %}
<div class="card">
    <h5 class="card-header">
        Related Reservations
    </h5>
    <div class="card-body">
        {% render_table related_reservations_table 'inc/table.html' %}
    </div>
</div>

netbox_reservations/templates/netbox_reservations/reservation.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Reservation</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th scope="row">Description</th>
              <td>{{ object.description|placeholder }}</td>
            </tr>
            <tr>
              <th scope="row">Status</th>
              <td>{{ object.status }}</td>
            </tr>
            <tr>
              <th scope="row">Is Draft</th>
              <td>{{ object.is_draft }}</td>
            </tr>
            <tr>
              <th scope="row">Contact</th>
              <td>
                {% if object.contact %}
                  <a href="{{ object.contact.get_absolute_url }}">{{ object.contact }}</a>
                {% else %}
                  {{ ''|placeholder }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Tenant</th>
              <td>
                {% if object.tenant %}
                  <a href="{{ object.tenant.get_absolute_url }}">{{ object.tenant }}</a>
                {% else %}
                  {{ ''|placeholder }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Starting Date</th>
              <td>{{ object.start_date }}</td>
            </tr>
            <tr>
              <th scope="row">End Date</th>
              <td>{{ object.end_date }}</td>
            </tr>
            <tr>
              <th scope="row">Claims</th>
              <td>{{ object.claims.count }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      <!--{% include 'inc/panels/comments.html' %}-->
    </div>
  </div>
  <div class="row">
  <div class="col col-md-12">
  <div class="card">
    <h5 class="card-header">
      Claims
    </h5>
    <div class="card-body table-responsive">
      {% render_table claims_table %}
    </div>
    <div class="card-footer">
      <a href="{% url 'plugins:netbox_reservations:claim_add' %}?reservation={{ object.id }}" type="button"
         class="btn btn-sm btn-success">
        <i class="mdi mdi-plus-thick"></i> Add Claim
      </a>
    </div>
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h5 class="card-header">
        Overlapping Reservations
      </h5>
      <div class="card-body table-responsive">
        <p>
        The following reservations overlap with this reservation. This does not mean that they conflict, but future
        conflicts may occur.
        </p>
        {% render_table conflict_table %}
      </div>
    </div>
  </div>
{% endblock content %}

netbox_reservations/templates/netbox_reservations/tag_extend_reservations.html
{% load render_table from django_tables2 %}
<div class="card">
    <h5 class="card-header">
        Related Reservations
    </h5>
    <div class="card-body">
        {% render_table related_reservations_table 'inc/table.html' %}
    </div>
</div>